spring:
  application:
    name: jfr-native-memory-leak

snowflake:
  url: hihbbpj-ng80025.snowflakecomputing.com
  username: JFR_TEST
  schema: JFR_TEST
  warehouse: COMPUTE_WH
  role: JFR_ROLE
  database: JFR_LEAK_TEST
